# Generated by Django 5.2.17 on 2026-09-28 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environments", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environments",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="environmentvariable",
            name="environment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variables",
                to="environments.environment",
            ),
        ),
        migrations.AddConstraint(
            model_name="environment",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_project_environment_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="environmentvariable",
            constraint=models.UniqueConstraint(
                fields=("environment", "key"), name="unique_environment_variable_key"
            ),
        ),
    ]
