import {
  ArrowLeft,
  ArrowRight,
  Camera,
  CheckSquare,
  Circle,
  Eraser,
  Eye,
  GitBranch,
  Link2,
  ListChecks,
  MousePointerClick,
  MousePointerSquareDashed,
  RefreshCw,
  Repeat,
  ScrollText,
  TextCursorInput,
  TextSelect,
  Timer,
  Type,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const ACTION_ICONS: Record<string, LucideIcon> = {
  open_url: Link2,
  refresh: RefreshCw,
  back: ArrowLeft,
  forward: ArrowRight,
  wait: Timer,
  screenshot: Camera,
  click: MousePointerClick,
  double_click: MousePointerClick,
  input_text: TextCursorInput,
  clear: Eraser,
  select: ListChecks,
  hover: MousePointerSquareDashed,
  scroll: ScrollText,
  assert_text: TextSelect,
  assert_element_exists: Circle,
  assert_element_visible: Eye,
  assert_url: Link2,
  assert_attribute: CheckSquare,
  assert_page_title: Type,
  conditional: GitBranch,
  retry: Repeat,
  wait_until: Timer,
};

export const CATEGORY_LABELS: Record<string, string> = {
  navigation: "Navigation",
  browser: "Browser",
  interaction: "Interaction",
  assertion: "Assertions",
  control: "Control",
};
